version: "3"
networks:
  database:
  queue:

services:
  db:
    build: ./docker/database
    restart: always
    ports:
      - 5432:5432
    networks:
      - database
  migration:
    image: python:3.8-slim-buster
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && flask db upgrade"
    volumes:
      - ./:/app
    environment:
      DB_SERVER: db
      REDIS_URL: redis://redis
      FLASK_APP: run_app.py
    depends_on:
      - db
    networks:
      - database
  worker:
    build:
      context: ./
      dockerfile: ./docker/worker/Dockerfile
    environment:
      DB_SERVER: db
      REDIS_URL: redis://redis
    networks:
      - database
      - queue
    depends_on:
      - db
      - redis
  app:
    build:
      context: ./
      dockerfile: ./docker/a55_api/Dockerfile
    ports:
      - 5000:8080
    environment:
      DB_SERVER: db
      REDIS_URL: redis://redis
    networks:
      - database
      - queue
    depends_on:
      - migration
      - db
      - redis
  redis:
    image: redis:5.0
    ports:
      - 6379:6379
    networks:
      - queue
